import { ChannelAdapter } from './channels/types';

export type MessageContentType =
  | 'text'
  | 'image'
  | 'voice'
  | 'file'
  | 'audio'
  | 'video'
  | 'unknown';

export interface MessageAttachment {
  type: 'image' | 'file' | 'audio' | 'video';
  /** Original file/image key from the channel (e.g. Feishu image_key / file_key) */
  fileKey?: string;
  fileName?: string;
  mimeType?: string;
  /** Base64-encoded raw bytes, if downloaded */
  base64?: string;
}

export interface MessageContent {
  type: MessageContentType;
  text?: string;
  mediaUrl?: string;
  attachments?: MessageAttachment[];
}

/** Canonical message format flowing through iris */
export interface IrisMessage {
  /** Unique message ID (generated by iris) */
  id: string;
  /** Source channel */
  channel: string;
  /** User ID within the source channel */
  channelUserId: string;
  /** Session/conversation ID — defaults to `{channel}:{channelUserId}` */
  sessionId: string;
  /** Normalised content */
  content: MessageContent;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Original raw payload from the channel — preserved for advanced use */
  raw: unknown;
}

/** Context that flows through the plugin pipeline */
export interface PluginContext {
  message: IrisMessage;
  /** Plugins write business data here; all data is forwarded to the AI backend */
  business: Record<string, unknown>;
}

/** Request sent to an AI backend */
export interface BackendRequest {
  message: IrisMessage;
  /** Aggregated business context injected by plugins */
  context: Record<string, unknown>;

  /**
   * Current channel adapter. Async backends can call channelAdapter.reply()
   * directly when the downstream reply arrives.
   */
  channelAdapter: ChannelAdapter;
}
