import { ChannelAdapter } from './channels/types';

export type MessageContentPart =
  | {
      type: 'text';
      text: string;
    }
  | {
      type: 'image_url';
      image_url: {
        url: string;
        detail?: string;
      };
    }
  | {
      type: 'input_audio';
      input_audio: {
        data: string;
        format?: string;
      };
    }
  | {
      type: 'file';
      file: {
        file_id?: string;
        filename?: string;
        file_data?: string;
        mimetype?: string;
      };
    };

export type MessageType = 'message' | 'message_update';

/** Canonical message format flowing through iris */
export interface IrisMessage {
  /** Unique message ID (generated by iris) */
  id: string;
  type: MessageType;
  /** Source channel */
  channel: string;
  /** User ID within the source channel */
  channelUserId: string;
  /** Session/conversation ID — defaults to `{channel}:{channelUserId}` */
  sessionId: string;
  /** Normalized OpenAI-compatible content parts */
  content: MessageContentPart[];
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Original raw payload from the channel — preserved for advanced use */
  raw: unknown;
  /** Aggregated business context injected by plugins */
  context?: Record<string, unknown>;
}

/** Context that flows through the plugin pipeline */
export interface PluginContext {
  message: IrisMessage;
  /** Plugins write business data here; all data is forwarded to the AI backend */
  business: Record<string, unknown>;
}

/** Request sent to an AI backend */
export interface BackendRequest {
  message: IrisMessage;

  /**
   * Current channel adapter. Async backends can call channelAdapter.reply()
   * directly when the downstream reply arrives.
   */
  channelAdapter: ChannelAdapter;
}

export function extractTextFromContentParts(parts: MessageContentPart[]): string {
  return parts
    .filter((part): part is Extract<MessageContentPart, { type: 'text' }> => part.type === 'text')
    .map((part) => part.text)
    .join('');
}
